[package]
name = "foc"
version = "0.1.0"
edition = "2024"


[features]
defmt = ["dep:defmt"]

[dependencies]
defmt = {version = "1.0.1", optional = true}
units = {path = "../../utils/units"}
pid = {path = "../../utils/pid"}